# Generated by Django 2.2.5 on 2019-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.PositiveIntegerField()),
                ('amount_of_quest', models.PositiveIntegerField()),
            ],
        ),
    ]
