# Generated by Django 2.2.5 on 2019-09-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_id',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='status',
        ),
    ]
