# Generated by Django 2.2.5 on 2019-09-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190920_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_time',
        ),
    ]
