# Generated by Django 2.2.5 on 2019-10-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20191012_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='amount_of_choices',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
