# Generated by Django 2.2.5 on 2019-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20191001_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_big_card',
            field=models.BooleanField(default=False),
        ),
    ]
