# Generated by Django 2.2.5 on 2019-10-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20191013_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='amount_of_choices',
        ),
    ]
