# Generated by Django 2.2.5 on 2019-10-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_is_big_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='end_time',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='start_time',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='status',
        ),
        migrations.AddField(
            model_name='poll',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='amount_of_answers',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True)),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Question')),
            ],
        ),
    ]
