# Generated by Django 2.2.5 on 2019-10-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_question_amount_of_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='amount_of_questions',
        ),
    ]
