# Generated by Django 2.2.5 on 2019-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20191017_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/polls/'),
        ),
    ]
